server:
  port: 7071
  servlet:
    context-path: /ptm-login

spring:
  application:
    name: ptm-login
    
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000

